### ISSUE TITLE
Can't change the length on surface tab

### ISSUE THREAD

**Issue by AndyPrasetyo** [clarkx/Parquet#3]
Hi Clarkx, i have issue that i can't change the length more than 1 m, it's stuck on 1 m. 
Please help, i am new using this add on. 

The screenshot attached
![screenshot_21](https://user-images.githubusercontent.com/17880132/46275190-43e26480-c586-11e8-9bbc-e52d9eb9801f.jpg)

**Comment by clarkx** [comment]
Hi Andy, sorry for the delay. This is because of the unit system. 
The length has been declared with a max value of 100. 
If you change the unit system from meters to centimeters, you will have 100 centimeters, which is 1 meter. To avoïd this problem, be sure to be in meters.

Thanks for the report ! 👍 I will try to fix it

**Comment by clarkx** [comment]
Fixed !
